name: ci

on:
  workflow_dispatch:
  # on push, we will run ci then also push built images
  push:
    branches:
      - main

jobs:
  ci-build-and-push:
    name: ci-build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # This enables the creation of a builder instance with persistent cache
          driver-opts: |
            image=moby/buildkit:latest
            network=host
      
      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.digitalocean.com/dbr-cr/runpod_whisper:${{ github.sha }}
          # Enhanced cache settings
          cache-from: |
            type=gha,scope=runpod_whisper
            type=registry,ref=registry.digitalocean.com/dbr-cr/runpod_whisper:latest
          cache-to: type=gha,scope=runpod_whisper,mode=max 